backend:
  name: github
  repo: jquintero-innmedios/innmedios
  branch: main

media_folder: fotos
public_folder: /fotos

locale: es

collections:
  - name: blog
    label: Blog
    folder: blog/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Título, name: titulo, widget: string }
      - { label: Categoría, name: categoria, widget: select, options: [Documental, Cultura, Innovación, Territorio, Comunicación, Producción] }
      - { label: Fecha, name: fecha, widget: datetime, format: DD MMM YYYY, date_format: DD MMM YYYY, time_format: false }
      - { label: Tiempo de lectura, name: lectura, widget: number, default: 3 }
      - { label: Imagen de portada, name: imagen, widget: image }
      - { label: Resumen, name: resumen, widget: text }
      - { label: Contenido, name: body, widget: markdown }
